config/routes.rb
Rails.application.routes.draw do
  resources :usuarios

  resources :categoria_de_servicos

  resources :sessions

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_and_belongs_to_many  :categoria_de_servicos
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	has_secure_password
	validates_presence_of :password, :on => :create
	validates_uniqueness_of :email

	attr_accessor :password_confirmation

	def avatar_url_thumb
    	avatar.url(:thumb)
	end

	def avatar_url_medium
    	avatar.url(:medium)
	end

	def avatar_url
    	avatar.url
	end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  #before_action :authorize

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
    @categorias = CategoriaDeServico.all
  end

  # GET /usuarios/1/edit
  def edit
    @categorias = CategoriaDeServico.all
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :password, :telefone, :avatar, :facebook_avatar_url, :categoria_de_servico_ids => [])
    end

end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for @usuario, :html => { :multipart => true } do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= image_tag @usuario.avatar.url(:thumb) %>
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :categoria_de_servico %><br>
    <%= f.collection_select :categoria_de_servico_ids, @categorias, :id, :titulo, {}, 
    {:multiple => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Password</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= image_tag(usuario.avatar.url(:thumb), :alt => "Avatar") %></td>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.password %></td>
        <td><%= usuario.telefone %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @usuario.avatar.url %>
<%= image_tag @usuario.avatar.url(:medium) %>
<%= image_tag @usuario.avatar.url(:thumb) %>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @usuario.password %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @usuario.telefone %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>