config/routes.rb
Rails.application.routes.draw do
  resources :usuarios

  resources :categoria_de_servicos

  resources :sessions

end

app/models/categoria_de_servico.rb
class CategoriaDeServico < ActiveRecord::Base
	has_and_belongs_to_many :usuarios
end

app/controllers/categoria_de_servicos_controller.rb
class CategoriaDeServicosController < ApplicationController
  before_action :set_categoria_de_servico, only: [:show, :edit, :update, :destroy]

  # GET /categoria_de_servicos
  # GET /categoria_de_servicos.json
  def index
    @categoria_de_servicos = CategoriaDeServico.all
  end

  # GET /categoria_de_servicos/1
  # GET /categoria_de_servicos/1.json
  def show
  end

  # GET /categoria_de_servicos/new
  def new
    @categoria_de_servico = CategoriaDeServico.new
  end

  # GET /categoria_de_servicos/1/edit
  def edit
  end

  # POST /categoria_de_servicos
  # POST /categoria_de_servicos.json
  def create
    @categoria_de_servico = CategoriaDeServico.new(categoria_de_servico_params)

    respond_to do |format|
      if @categoria_de_servico.save
        format.html { redirect_to @categoria_de_servico, notice: 'Categoria de servico was successfully created.' }
        format.json { render :show, status: :created, location: @categoria_de_servico }
      else
        format.html { render :new }
        format.json { render json: @categoria_de_servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria_de_servicos/1
  # PATCH/PUT /categoria_de_servicos/1.json
  def update
    respond_to do |format|
      if @categoria_de_servico.update(categoria_de_servico_params)
        format.html { redirect_to @categoria_de_servico, notice: 'Categoria de servico was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria_de_servico }
      else
        format.html { render :edit }
        format.json { render json: @categoria_de_servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria_de_servicos/1
  # DELETE /categoria_de_servicos/1.json
  def destroy
    @categoria_de_servico.destroy
    respond_to do |format|
      format.html { redirect_to categoria_de_servicos_url, notice: 'Categoria de servico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria_de_servico
      @categoria_de_servico = CategoriaDeServico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_de_servico_params
      params.require(:categoria_de_servico).permit(:titulo)
    end
end

app/helpers/categoria_de_servicos_helper.rb
module CategoriaDeServicosHelper
end

app/views/categoria_de_servicos/_form.html.erb
<%= form_for(@categoria_de_servico) do |f| %>
  <% if @categoria_de_servico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria_de_servico.errors.count, "error") %> prohibited this categoria_de_servico from being saved:</h2>

      <ul>
      <% @categoria_de_servico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoria_de_servicos/edit.html.erb
<h1>Editing categoria_de_servico</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria_de_servico %> |
<%= link_to 'Back', categoria_de_servicos_path %>

app/views/categoria_de_servicos/index.html.erb
<h1>Listing categoria_de_servicos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria_de_servicos.each do |categoria_de_servico| %>
      <tr>
        <td><%= categoria_de_servico.titulo %></td>
        <td><%= link_to 'Show', categoria_de_servico %></td>
        <td><%= link_to 'Edit', edit_categoria_de_servico_path(categoria_de_servico) %></td>
        <td><%= link_to 'Destroy', categoria_de_servico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categoria de servico', new_categoria_de_servico_path %>

app/views/categoria_de_servicos/new.html.erb
<h1>New categoria_de_servico</h1>

<%= render 'form' %>

<%= link_to 'Back', categoria_de_servicos_path %>

app/views/categoria_de_servicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @categoria_de_servico.titulo %>
</p>

<%= link_to 'Edit', edit_categoria_de_servico_path(@categoria_de_servico) %> |
<%= link_to 'Back', categoria_de_servicos_path %>